version: "3"

services:

  api:
    build: ./api
    ports:
      - '8080:8080'
    restart: always
    container_name: api

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    restart: always
    container_name: frontend

  db:
    image: mongo:bionic
    ports:
      - '27017:27017'
    volumes:
      - database:/data/db
    restart: always
    container_name: db

volumes:
  database:
